package com.wision.util.poi;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import org.apache.poi.xwpf.usermodel.XWPFDocument;

public class TestExportWord {
    public static void main(String[] args) throws Exception {
        ExportWord ew = new ExportWord();
        XWPFDocument document = ew.createXWPFDocument();
        List<List<Object>> list = new ArrayList<List<Object>>();
        List<Object> tempList = new ArrayList<Object>();
        tempList.add("申请单位基本情况");
        list.add(tempList);
        tempList = new ArrayList<Object>();
        tempList.add("单位名称");
        tempList.add("xxxxxxxxxxxx");
        list.add(tempList);
        tempList = new ArrayList<Object>();
        tempList.add("所在市(地)");
        tempList.add("xxxxxxxxxxxx");
        tempList.add("所在区(县)");
        tempList.add("xxxxxxxxxxxx");
        list.add(tempList);
        tempList = new ArrayList<Object>();
        tempList.add("单位地址");
        tempList.add("xxxxxxxxxxxx");
        list.add(tempList);
        tempList = new ArrayList<Object>();
        tempList.add("统一社会信用代码");
        tempList.add("xxxxxxxxxxxx");
        tempList.add("法定代表人");
        tempList.add("xxxxxxxxxxxx");
        list.add(tempList);
        tempList = new ArrayList<Object>();
        tempList.add("邮政编码");
        tempList.add("xxxxxxxxxxxx");
        tempList.add("电话");
        tempList.add("xxxxxxxxxxxx");
        list.add(tempList);
        tempList = new ArrayList<Object>();
        tempList.add("传真");
        tempList.add("xxxxxxxxxxxx");
        tempList.add("电子邮箱");
        tempList.add("xxxxxxxxxxxx");
        list.add(tempList);
        tempList = new ArrayList<Object>();
        tempList.add("固定资产（万元）");
        tempList.add("xxxxxxxxxxxx");
        tempList.add("注册资金（万元）");
        tempList.add("xxxxxxxxxxxx");
        list.add(tempList);
        tempList = new ArrayList<Object>();
        tempList.add("申请单位资源");
        list.add(tempList);
        tempList = new ArrayList<Object>();
        tempList.add("占地面积（m3）");
        tempList.add("xxxxxxxxxxxx");
        tempList.add("厂房面积（m3）");
        tempList.add("xxxxxxxxxxxx");
        list.add(tempList);
        tempList = new ArrayList<Object>();
        tempList.add("曝光室面积（m3）");
        tempList.add("xxxxxxxxxxxx");
        tempList.add("设计人员数");
        tempList.add("xxxxxxxxxxxx");
        list.add(tempList);
        tempList = new ArrayList<Object>();
        tempList.add("检查人员数");
        tempList.add("xxxxxxxxxxxx");
        tempList.add("无损检测人员数");
        tempList.add("xxxxxxxxxxxx");
        list.add(tempList);
        tempList = new ArrayList<Object>();
        tempList.add("焊接人员数");
        tempList.add("xxxxxxxxxxxx");
        tempList.add("其他专业人员数量");
        tempList.add("xxxxxxxxxxxx");
        list.add(tempList);
        tempList = new ArrayList<Object>();
        tempList.add("各部门人员组成");
        list.add(tempList);
        tempList = new ArrayList<Object>();
        tempList.add("部     门");
        tempList.add("部门负责人");
        tempList.add("");
        tempList.add("部门人员数");
        list.add(tempList);

        Map<String, Object> dataList = new HashMap<String, Object>();
        dataList.put("TITLE", "");
        dataList.put("TABLEDATA", list);
        ew.exportCheckWord(dataList, document, "D:/Workspaces/IdeaProjects/hsiri/src/main/resources/templates/expWordTest.docx");
        System.out.println("文档生成成功");
    }
}
